services:
  db:
    image: postgres:16-alpine
    container_name: taskapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskapidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskapidb"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  
volumes: 
  pgdata:
  